version: '3.9'

services:
  app:
    platform: linux/amd64
    build: .
    container_name: brain_trust
    working_dir: /app
    volumes:
      - .:/app:cached
    # keep container alive for VSÂ Code
    entrypoint: ["tail", "-f", "/dev/null"]
